### ISSUE TITLE
Use fast burger image as favicon on pages

### ISSUE THREAD

**Issue by joaovictor3g** [joaovictor3g/fast-burger#11]
If necessary, edit the image so that it fits on the page tab.
![Captura de tela de 2021-10-04 21-54-34](https://user-images.githubusercontent.com/55103977/135943821-7fec8e62-3d31-4f34-929f-55c5e4b4f5a1.png)

Image that you could use:
![Captura de tela de 2021-10-04 21-54-55](https://user-images.githubusercontent.com/55103977/135943857-f9b51203-1457-4c41-87ae-0b9efb56ea78.png)
 
Any questions just comment below :) I'll be happy to help

**Comment by LucasRobs** [comment]
hi @joaovictor3g  i would like to solve this problem, could you assign me?

**Comment by LucasRobs** [comment]
can you give me more information on how the result should be

**Comment by joaovictor3g** [comment]
> hi @joaovictor3g i would like to solve this problem, could you assign me?

of course, feel free to contribute

**Comment by joaovictor3g** [comment]
> can you give me more information on how the result should be

I'll send to you the figma UI project, this way you can pick up the image and edit it, whatever you want to do.
https://www.figma.com/file/aPuJZFYNr41peVA2U5wA2O/Fast-Burguer?node-id=0%3A1
